using ErpSystem.BuildingBlocks.Domain;

namespace ErpSystem.Mrp.Domain;

/// <summary>
/// Procurement Suggestion - Generated by MRP engine when reordering is needed
/// </summary>
public class ProcurementSuggestion : AggregateRoot<Guid>
{
    public string TenantId { get; private set; } = string.Empty;
    public string MaterialId { get; private set; } = string.Empty;
    public string WarehouseId { get; private set; } = string.Empty;
    public decimal SuggestedQuantity { get; private set; }
    public DateTime SuggestedDate { get; private set; }
    public ProcurementSuggestionStatus Status { get; private set; }
    public string ReorderingRuleId { get; private set; } = string.Empty;
    public string? GeneratedPurchaseOrderId { get; private set; }
    public ProcurementCalculation? Calculation { get; private set; }

    public static ProcurementSuggestion Create(
        Guid id,
        string tenantId,
        string materialId,
        string warehouseId,
        decimal suggestedQuantity,
        DateTime suggestedDate,
        string reorderingRuleId,
        ProcurementCalculation calculation)
    {
        ProcurementSuggestion suggestion = new();
        suggestion.ApplyChange(new ProcurementSuggestionCreatedEvent(
            id,
            tenantId,
            materialId,
            warehouseId,
            suggestedQuantity,
            suggestedDate,
            reorderingRuleId,
            calculation,
            DateTime.UtcNow));
        return suggestion;
    }

    public void Approve(string approvedBy)
    {
        if (this.Status != ProcurementSuggestionStatus.Pending)
            throw new InvalidOperationException($"Cannot approve suggestion in status {this.Status}");

        this.ApplyChange(new ProcurementSuggestionApprovedEvent(this.Id,
            approvedBy,
            DateTime.UtcNow));
    }

    public void Reject(string rejectedBy, string reason)
    {
        if (this.Status != ProcurementSuggestionStatus.Pending)
            throw new InvalidOperationException($"Cannot reject suggestion in status {this.Status}");

        this.ApplyChange(new ProcurementSuggestionRejectedEvent(this.Id,
            rejectedBy,
            reason,
            DateTime.UtcNow));
    }

    public void MarkAsConverted(string purchaseOrderId)
    {
        if (this.Status != ProcurementSuggestionStatus.Approved)
            throw new InvalidOperationException("Only approved suggestions can be converted to PO");

        this.ApplyChange(new ProcurementSuggestionConvertedEvent(this.Id,
            purchaseOrderId,
            DateTime.UtcNow));
    }

    protected override void Apply(IDomainEvent @event)
    {
        switch (@event)
        {
            case ProcurementSuggestionCreatedEvent e:
                this.Id = e.AggregateId;
                this.TenantId = e.TenantId;
                this.MaterialId = e.MaterialId;
                this.WarehouseId = e.WarehouseId;
                this.SuggestedQuantity = e.SuggestedQuantity;
                this.SuggestedDate = e.SuggestedDate;
                this.ReorderingRuleId = e.ReorderingRuleId;
                this.Calculation = e.Calculation;
                this.Status = ProcurementSuggestionStatus.Pending;
                break;
            case ProcurementSuggestionApprovedEvent:
                this.Status = ProcurementSuggestionStatus.Approved;
                break;
            case ProcurementSuggestionRejectedEvent:
                this.Status = ProcurementSuggestionStatus.Rejected;
                break;
            case ProcurementSuggestionConvertedEvent e:
                this.Status = ProcurementSuggestionStatus.Converted;
                this.GeneratedPurchaseOrderId = e.PurchaseOrderId;
                break;
        }
    }
}

public enum ProcurementSuggestionStatus
{
    Pending = 1,
    Approved = 2,
    Rejected = 3,
    Converted = 4  // Converted to Purchase Order
}

/// <summary>
/// Calculation details for procurement suggestion
/// </summary>
public record ProcurementCalculation(
    decimal CurrentOnHand,
    decimal Reserved,
    decimal Available,
    decimal IncomingProcurement,
    decimal IncomingProduction,
    decimal ForecastedAvailable,
    decimal MinQuantity,
    decimal MaxQuantity,
    string Reason);

// Domain Events
public record ProcurementSuggestionCreatedEvent(
    Guid AggregateId,
    string TenantId,
    string MaterialId,
    string WarehouseId,
    decimal SuggestedQuantity,
    DateTime SuggestedDate,
    string ReorderingRuleId,
    ProcurementCalculation Calculation,
    DateTime OccurredAt) : IDomainEvent
{
    public Guid EventId { get; } = Guid.NewGuid();
    public DateTime OccurredOn => this.OccurredAt;
}

public record ProcurementSuggestionApprovedEvent(
    Guid AggregateId,
    string ApprovedBy,
    DateTime OccurredAt) : IDomainEvent
{
    public Guid EventId { get; } = Guid.NewGuid();
    public DateTime OccurredOn => this.OccurredAt;
}

public record ProcurementSuggestionRejectedEvent(
    Guid AggregateId,
    string RejectedBy,
    string Reason,
    DateTime OccurredAt) : IDomainEvent
{
    public Guid EventId { get; } = Guid.NewGuid();
    public DateTime OccurredOn => this.OccurredAt;
}

public record ProcurementSuggestionConvertedEvent(
    Guid AggregateId,
    string PurchaseOrderId,
    DateTime OccurredAt) : IDomainEvent
{
    public Guid EventId { get; } = Guid.NewGuid();
    public DateTime OccurredOn => this.OccurredAt;
}

